### ISSUE TITLE
是否可以读取github项目或者类似线上仓库中的md，并且监听推送更新md内容

### ISSUE THREAD

**Issue by justin5562587** [springcloudy/my-notes#1]
期望支持以下功能
1. md目录配置连接到一个线上文档仓库
2. 根据仓库文件夹的分类可视化的展示md的文件的目录树结构
3. 并且希望能支持分支的切换查看，这样可以查看过去的release和最新的update
4. 监听到推送后更新最新的md内容到view进行展示，并且设置页面提醒推送

**Comment by reliveyy** [comment]
仓库自动更新可以使用 GitHub Webhooks，考虑添加一个新的配置属性 

```
--app.notesRepo=git@github.com:reliveyy/notes.git
--app.notesRepo=https://github.com/reliveyy/notes.git
```

来制定仓库地址，然后本地也需要克隆一份到 `--app.notesDir` 下面
